CREATE TABLE IF NOT EXISTS Genre ( 
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Performer (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS GenrePerformer (
	id SERIAL PRIMARY KEY,
	genre_id INTEGER NOT NULL REFERENCES Genre(id),
	performer_id INTEGER NOT NULL REFERENCES Performer(id)
);

CREATE TABLE IF NOT EXISTS Album (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	year_release INTERVAL YEAR NOT NULL	
);

CREATE TABLE IF NOT EXISTS PerformerAlbum (
	id SERIAL PRIMARY KEY,
	performer_id INTEGER NOT NULL REFERENCES Performer(id),
	album_id INTEGER NOT NULL REFERENCES Album(id)
);

CREATE TABLE IF NOT EXISTS Track (
	id SERIAL PRIMARY KEY,
	album_id INTEGER NOT NULL REFERENCES Album(id),
	name VARCHAR(40) NOT NULL,
	duration INTERVAL MINUTE TO SECOND NOT NULL
);

CREATE TABLE IF NOT EXISTS Collection ( 
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	year_release INTERVAL YEAR NOT NULL
);

CREATE TABLE IF NOT EXISTS CollectionTrack (
	id SERIAL PRIMARY KEY,
	collection_id INTEGER NOT NULL REFERENCES Collection(id),
	track_id INTEGER NOT NULL REFERENCES Track(id)	
);


